import {
  Dna, Brain, FlaskConical, Heart, Palette, GraduationCap,
  User, Zap, Utensils, Scissors, Network, BrainCircuit,
  Clock, Sparkles, Users, TreePine, Microscope, Search,
  Beaker, BarChart3, Globe, Pill, Flower2, Timer,
  Syringe, Bug, BookOpen, Rocket, Shield, Shapes,
} from 'lucide-react'

export enum ToolCategory {
  PERSONAL = 'PERSONAL',
  ANALYSIS = 'ANALYSIS',
  RESEARCH = 'RESEARCH',
  HEALTH = 'HEALTH',
  DESIGN = 'DESIGN',
  EDUCATION = 'EDUCATION',
}

export const CATEGORY_META: Record<ToolCategory, { label: string; labelEs: string; icon: typeof Dna; color: string }> = {
  [ToolCategory.PERSONAL]: { label: 'Personal', labelEs: 'Personal', icon: User, color: 'cyan' },
  [ToolCategory.ANALYSIS]: { label: 'Analysis', labelEs: 'Analisis', icon: BarChart3, color: 'blue' },
  [ToolCategory.RESEARCH]: { label: 'Research', labelEs: 'Investigacion', icon: FlaskConical, color: 'purple' },
  [ToolCategory.HEALTH]: { label: 'Health', labelEs: 'Salud', icon: Heart, color: 'green' },
  [ToolCategory.DESIGN]: { label: 'Design', labelEs: 'Diseno', icon: Palette, color: 'orange' },
  [ToolCategory.EDUCATION]: { label: 'Education', labelEs: 'Educacion', icon: GraduationCap, color: 'yellow' },
}

export interface ToolMeta {
  id: string
  name: string
  nameEs: string
  description: string
  descriptionEs: string
  category: ToolCategory
  icon: typeof Dna
  color: string
  complexity: 'basic' | 'intermediate' | 'advanced'
  estimatedTime: string
  premium: boolean
  requiresApiKey: boolean
}

export const TOOLS_METADATA: ToolMeta[] = [
  // PERSONAL
  {
    id: 'my-dna-personal',
    name: 'My DNA Personal',
    nameEs: 'Mi ADN Personal',
    description: 'Upload and analyze your DNA file',
    descriptionEs: 'Sube y analiza tu archivo de ADN',
    category: ToolCategory.PERSONAL,
    icon: Dna,
    color: 'cyan',
    complexity: 'basic',
    estimatedTime: '2-5 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'genetic-superpowers',
    name: 'Genetic Superpowers',
    nameEs: 'Superpoderes Geneticos',
    description: 'Discover your unique genetic strengths',
    descriptionEs: 'Descubre tus fortalezas geneticas unicas',
    category: ToolCategory.PERSONAL,
    icon: Zap,
    color: 'yellow',
    complexity: 'basic',
    estimatedTime: '1-2 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'genetic-diet',
    name: 'Genetic Diet',
    nameEs: 'Dieta Genetica',
    description: 'Personalized nutrition based on your genes',
    descriptionEs: 'Nutricion personalizada basada en tus genes',
    category: ToolCategory.HEALTH,
    icon: Utensils,
    color: 'green',
    complexity: 'basic',
    estimatedTime: '2-3 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'capabilities-optimizer',
    name: 'Capabilities Optimizer',
    nameEs: 'Optimizador de Capacidades',
    description: 'Optimize your performance based on genetics',
    descriptionEs: 'Optimiza tu rendimiento basado en genetica',
    category: ToolCategory.PERSONAL,
    icon: Sparkles,
    color: 'purple',
    complexity: 'intermediate',
    estimatedTime: '3-5 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'couple-compatibility',
    name: 'Couple Compatibility',
    nameEs: 'Compatibilidad de Pareja',
    description: 'Analyze genetic compatibility between partners',
    descriptionEs: 'Analiza la compatibilidad genetica entre parejas',
    category: ToolCategory.PERSONAL,
    icon: Users,
    color: 'pink',
    complexity: 'basic',
    estimatedTime: '2-3 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'beneficial-variants-library',
    name: 'Beneficial Variants Library',
    nameEs: 'Biblioteca de Variantes Beneficiosas',
    description: 'Browse known beneficial genetic variants',
    descriptionEs: 'Explora variantes geneticas beneficiosas conocidas',
    category: ToolCategory.PERSONAL,
    icon: BookOpen,
    color: 'emerald',
    complexity: 'basic',
    estimatedTime: '1-2 min',
    premium: false,
    requiresApiKey: false,
  },
  // ANALYSIS
  {
    id: 'splicing-predictor',
    name: 'Splicing Predictor',
    nameEs: 'Predictor de Splicing',
    description: 'Predict RNA splicing effects of variants',
    descriptionEs: 'Predice efectos de splicing de variantes',
    category: ToolCategory.ANALYSIS,
    icon: Scissors,
    color: 'blue',
    complexity: 'advanced',
    estimatedTime: '3-5 min',
    premium: false,
    requiresApiKey: true,
  },
  {
    id: 'regulatory-networks',
    name: 'Regulatory Networks',
    nameEs: 'Redes Regulatorias',
    description: 'Explore gene regulatory networks',
    descriptionEs: 'Explora redes regulatorias de genes',
    category: ToolCategory.ANALYSIS,
    icon: Network,
    color: 'indigo',
    complexity: 'advanced',
    estimatedTime: '5-10 min',
    premium: false,
    requiresApiKey: true,
  },
  {
    id: 'batch-analyzer',
    name: 'Batch Analyzer',
    nameEs: 'Analizador por Lotes',
    description: 'Analyze multiple variants at once',
    descriptionEs: 'Analiza multiples variantes a la vez',
    category: ToolCategory.ANALYSIS,
    icon: BarChart3,
    color: 'blue',
    complexity: 'advanced',
    estimatedTime: '5-15 min',
    premium: true,
    requiresApiKey: true,
  },
  {
    id: 'genome-comparator',
    name: 'Genome Comparator',
    nameEs: 'Comparador de Genomas',
    description: 'Compare variants across genomes',
    descriptionEs: 'Compara variantes entre genomas',
    category: ToolCategory.ANALYSIS,
    icon: Shapes,
    color: 'violet',
    complexity: 'advanced',
    estimatedTime: '5-10 min',
    premium: false,
    requiresApiKey: true,
  },
  {
    id: 'aging-predictor',
    name: 'Aging Predictor',
    nameEs: 'Predictor de Envejecimiento',
    description: 'Predict aging biomarkers from variants',
    descriptionEs: 'Predice biomarcadores de envejecimiento',
    category: ToolCategory.ANALYSIS,
    icon: Clock,
    color: 'amber',
    complexity: 'intermediate',
    estimatedTime: '3-5 min',
    premium: false,
    requiresApiKey: true,
  },
  {
    id: 'aging-error-corrector',
    name: 'Aging Error Corrector',
    nameEs: 'Corrector de Errores de Envejecimiento',
    description: 'Identify and correct aging-related errors',
    descriptionEs: 'Identifica y corrige errores de envejecimiento',
    category: ToolCategory.ANALYSIS,
    icon: Shield,
    color: 'teal',
    complexity: 'advanced',
    estimatedTime: '5-8 min',
    premium: false,
    requiresApiKey: false,
  },
  // RESEARCH
  {
    id: 'drug-target-finder',
    name: 'Drug Target Finder',
    nameEs: 'Buscador de Dianas Farmacologicas',
    description: 'Discover potential drug targets',
    descriptionEs: 'Descubre posibles dianas farmacologicas',
    category: ToolCategory.RESEARCH,
    icon: Pill,
    color: 'rose',
    complexity: 'advanced',
    estimatedTime: '5-10 min',
    premium: true,
    requiresApiKey: true,
  },
  {
    id: 'crispr-simulator',
    name: 'CRISPR Simulator',
    nameEs: 'Simulador CRISPR',
    description: 'Simulate CRISPR gene editing outcomes',
    descriptionEs: 'Simula resultados de edicion genetica CRISPR',
    category: ToolCategory.RESEARCH,
    icon: Scissors,
    color: 'red',
    complexity: 'advanced',
    estimatedTime: '5-10 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'virtual-lab',
    name: 'Virtual Lab',
    nameEs: 'Laboratorio Virtual',
    description: 'Run virtual genomic experiments',
    descriptionEs: 'Ejecuta experimentos genomicos virtuales',
    category: ToolCategory.RESEARCH,
    icon: Beaker,
    color: 'cyan',
    complexity: 'advanced',
    estimatedTime: '10-20 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'organism-designer',
    name: 'Organism Designer',
    nameEs: 'Disenador de Organismos',
    description: 'Design custom organisms with gene editing',
    descriptionEs: 'Disena organismos personalizados',
    category: ToolCategory.DESIGN,
    icon: Flower2,
    color: 'lime',
    complexity: 'advanced',
    estimatedTime: '10-20 min',
    premium: true,
    requiresApiKey: false,
  },
  // HEALTH
  {
    id: 'pharmacogenomics',
    name: 'Pharmacogenomics',
    nameEs: 'Farmacogenomica',
    description: 'Drug response predictions based on genetics',
    descriptionEs: 'Predicciones de respuesta a farmacos',
    category: ToolCategory.HEALTH,
    icon: Pill,
    color: 'emerald',
    complexity: 'intermediate',
    estimatedTime: '3-5 min',
    premium: false,
    requiresApiKey: true,
  },
  {
    id: 'family-risk-assessment',
    name: 'Family Risk Assessment',
    nameEs: 'Evaluacion de Riesgo Familiar',
    description: 'Assess hereditary disease risks',
    descriptionEs: 'Evalua riesgos de enfermedades hereditarias',
    category: ToolCategory.HEALTH,
    icon: Heart,
    color: 'red',
    complexity: 'intermediate',
    estimatedTime: '5-10 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'immune-response-predictor',
    name: 'Immune Response Predictor',
    nameEs: 'Predictor de Respuesta Inmune',
    description: 'Predict immune system responses',
    descriptionEs: 'Predice respuestas del sistema inmune',
    category: ToolCategory.HEALTH,
    icon: Shield,
    color: 'green',
    complexity: 'advanced',
    estimatedTime: '5-10 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'gene-therapy-companion',
    name: 'Gene Therapy Companion',
    nameEs: 'Companero de Terapia Genica',
    description: 'Explore gene therapy options',
    descriptionEs: 'Explora opciones de terapia genica',
    category: ToolCategory.HEALTH,
    icon: Syringe,
    color: 'blue',
    complexity: 'advanced',
    estimatedTime: '5-10 min',
    premium: true,
    requiresApiKey: false,
  },
  {
    id: 'microbiome-connector',
    name: 'Microbiome Connector',
    nameEs: 'Conector de Microbioma',
    description: 'Connect genetics with microbiome data',
    descriptionEs: 'Conecta genetica con datos de microbioma',
    category: ToolCategory.HEALTH,
    icon: Bug,
    color: 'lime',
    complexity: 'intermediate',
    estimatedTime: '3-5 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'epigenetic-clock',
    name: 'Epigenetic Clock',
    nameEs: 'Reloj Epigenetico',
    description: 'Measure biological age via epigenetics',
    descriptionEs: 'Mide la edad biologica via epigenetica',
    category: ToolCategory.HEALTH,
    icon: Timer,
    color: 'amber',
    complexity: 'intermediate',
    estimatedTime: '3-5 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'epigenetic-coach',
    name: 'Epigenetic Coach',
    nameEs: 'Coach Epigenetico',
    description: 'AI-powered epigenetic lifestyle coaching',
    descriptionEs: 'Coaching epigenetico con IA',
    category: ToolCategory.HEALTH,
    icon: BrainCircuit,
    color: 'purple',
    complexity: 'intermediate',
    estimatedTime: '5-15 min',
    premium: true,
    requiresApiKey: false,
  },
  {
    id: 'rare-variants-network',
    name: 'Rare Variants Network',
    nameEs: 'Red de Variantes Raras',
    description: 'Explore rare variant associations',
    descriptionEs: 'Explora asociaciones de variantes raras',
    category: ToolCategory.HEALTH,
    icon: Network,
    color: 'violet',
    complexity: 'advanced',
    estimatedTime: '5-10 min',
    premium: true,
    requiresApiKey: false,
  },
  // EDUCATION
  {
    id: 'ancestry-explorer',
    name: 'Ancestry Explorer',
    nameEs: 'Explorador de Ancestria',
    description: 'Explore your ancestral origins',
    descriptionEs: 'Explora tus origenes ancestrales',
    category: ToolCategory.EDUCATION,
    icon: Globe,
    color: 'emerald',
    complexity: 'basic',
    estimatedTime: '2-3 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'evolution-simulator',
    name: 'Evolution Simulator',
    nameEs: 'Simulador de Evolucion',
    description: 'Simulate evolutionary processes',
    descriptionEs: 'Simula procesos evolutivos',
    category: ToolCategory.EDUCATION,
    icon: TreePine,
    color: 'green',
    complexity: 'intermediate',
    estimatedTime: '5-10 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'genetic-detective',
    name: 'Genetic Detective',
    nameEs: 'Detective Genetico',
    description: 'Solve genetic puzzles and mysteries',
    descriptionEs: 'Resuelve puzzles y misterios geneticos',
    category: ToolCategory.EDUCATION,
    icon: Search,
    color: 'orange',
    complexity: 'basic',
    estimatedTime: '3-5 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'tree-of-life',
    name: 'Tree of Life',
    nameEs: 'Arbol de la Vida',
    description: 'Explore the evolutionary tree of life',
    descriptionEs: 'Explora el arbol evolutivo de la vida',
    category: ToolCategory.EDUCATION,
    icon: TreePine,
    color: 'emerald',
    complexity: 'basic',
    estimatedTime: '2-5 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'mind-genome-connector',
    name: 'Mind-Genome Connector',
    nameEs: 'Conector Mente-Genoma',
    description: 'Explore connections between mind and genes',
    descriptionEs: 'Explora conexiones entre mente y genes',
    category: ToolCategory.EDUCATION,
    icon: Brain,
    color: 'pink',
    complexity: 'intermediate',
    estimatedTime: '3-5 min',
    premium: false,
    requiresApiKey: false,
  },
  {
    id: 'future-simulator',
    name: 'Future Simulator',
    nameEs: 'Simulador del Futuro',
    description: 'Simulate future genetic scenarios',
    descriptionEs: 'Simula escenarios geneticos futuros',
    category: ToolCategory.EDUCATION,
    icon: Rocket,
    color: 'indigo',
    complexity: 'intermediate',
    estimatedTime: '3-5 min',
    premium: false,
    requiresApiKey: false,
  },
]

export function getToolsByCategory(category: ToolCategory): ToolMeta[] {
  return TOOLS_METADATA.filter((t) => t.category === category)
}

export function getToolById(id: string): ToolMeta | undefined {
  return TOOLS_METADATA.find((t) => t.id === id)
}

export function searchTools(query: string): ToolMeta[] {
  const q = query.toLowerCase().trim()
  if (!q) return TOOLS_METADATA
  return TOOLS_METADATA.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.nameEs.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.descriptionEs.toLowerCase().includes(q) ||
      t.id.includes(q)
  )
}

export function getCategoryCounts(): Record<ToolCategory, number> {
  const counts = {} as Record<ToolCategory, number>
  for (const cat of Object.values(ToolCategory)) {
    counts[cat] = TOOLS_METADATA.filter((t) => t.category === cat).length
  }
  return counts
}
